import { act, cleanup, render, screen, fireEvent } from '@testing-library/react'
import '@testing-library/jest-dom/vitest'
import { beforeEach, expect, test, vi } from 'vitest'
import StopBar from './StopBar'
import Teleop from './Teleop'
import { resetStop } from './control'

beforeEach(() => { cleanup(); vi.useFakeTimers(); vi.stubGlobal('crypto', { randomUUID: () => 'id' }); vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(JSON.stringify({ state: 'ACCEPTED', targets: [{ robot_id: 'robot_1', state: 'SUCCEEDED' }, { robot_id: 'robot_2', state: 'UNCONFIRMED' }] }), { status: 202 }))) })
test('stop polls command and renders per-target confirmation states', async () => { const mock=vi.mocked(fetch); mock.mockResolvedValueOnce(new Response(JSON.stringify({ command_id:'cmd-1', state:'ACCEPTED' }), { status:202 })).mockResolvedValueOnce(new Response(JSON.stringify({ targets:[{robot_id:'robot_1',state:'CONFIRMED'},{robot_id:'robot_2',state:'UNCONFIRMED'}] }), { status:200 })); render(<StopBar role="OPERATOR" lease={null} />); fireEvent.click(screen.getByText('전체 정지')); await act(async () => {}); await act(async () => { vi.advanceTimersByTime(250) }); expect(screen.getByText(/robot_1.*CONFIRMED/)).toBeInTheDocument(); expect(screen.getByText(/robot_2.*UNCONFIRMED/)).toBeInTheDocument() })
test('manual button disabled with hint while stop latched', () => {
  const mock = vi.mocked(fetch); mock.mockClear()
  render(<Teleop robotId="robot_1" lease="lease" mode="IDLE" stopLatched />)
  expect(screen.getByText('MANUAL 모드 전환')).toBeDisabled()
  expect(screen.getByText(/정지 해제 후 모드 전환 가능/)).toBeInTheDocument()
  expect(mock).not.toHaveBeenCalled()
})
test('stop bar states software-only stop clearly', () => {
  render(<StopBar role="OPERATOR" lease={null} />)
  expect(screen.getByText('정지')).toBeInTheDocument()
  expect(screen.queryByText('긴급 정지')).not.toBeInTheDocument()
  expect(screen.getByText(/물리 안전 장치가 아닙니다/)).toBeInTheDocument()
})
test('teleop press hold sends cadence and one zero on keyup', () => { class Socket { static sent: any[] = []; readyState=1; send(v: string) { Socket.sent.push(JSON.parse(v)) } close() {} } vi.stubGlobal('WebSocket', Socket); render(<Teleop robotId="robot_1" lease="lease" mode="MANUAL" />); const button=screen.getByText('전진'); fireEvent.pointerDown(button); act(() => vi.advanceTimersByTime(350)); fireEvent.pointerUp(button); expect(Socket.sent.length).toBe(5); expect(Socket.sent[Socket.sent.length - 1]).toMatchObject({ linear_mps: 0, angular_rps: 0 }); expect(Socket.sent.map(v=>v.seq)).toEqual([1,2,3,4,5]) })
test('teleop sends the held command when a newly opened socket becomes ready', () => { class Socket { static instance: Socket; static sent: any[] = []; readyState=0; onopen=()=>{}; onmessage=(_: MessageEvent)=>{}; onerror=()=>{}; onclose=()=>{}; constructor() { Socket.instance=this } open() { this.readyState=1; this.onopen() } send(v: string) { Socket.sent.push(JSON.parse(v)) } close() {} } vi.stubGlobal('WebSocket', Socket); render(<Teleop robotId="robot_1" lease="lease" mode="MANUAL" />); const button=screen.getByText('전진'); fireEvent.pointerDown(button); act(() => vi.advanceTimersByTime(100)); act(() => Socket.instance.open()); fireEvent.pointerUp(button); expect(Socket.sent.map(v=>v.linear_mps)).toEqual([.15, 0]) })
test('left turn sends a nonzero angular velocity within the watchdog limit', () => { class Socket { static sent: any[] = []; readyState=1; send(v: string) { Socket.sent.push(JSON.parse(v)) } close() {} } vi.stubGlobal('WebSocket', Socket); render(<Teleop robotId="robot_1" lease="lease" mode="MANUAL" />); const button=screen.getByText('좌회전'); fireEvent.pointerDown(button); expect(Socket.sent[0]).toMatchObject({ linear_mps: 0, angular_rps: .3 }); fireEvent.pointerUp(button); expect(Socket.sent[1]).toMatchObject({ linear_mps: 0, angular_rps: 0 }) })
test('teleop stops on window blur and does not duplicate interval', () => { class Socket { readyState=1; static sent:any[]=[]; send(v:string){Socket.sent.push(JSON.parse(v))} close(){} } vi.stubGlobal('WebSocket', Socket); render(<Teleop robotId="robot_1" lease="lease" mode="MANUAL" />); const b=screen.getByText('전진'); fireEvent.pointerDown(b); fireEvent.pointerDown(b); act(()=>vi.advanceTimersByTime(100)); fireEvent(window,new Event('blur')); expect(Socket.sent[Socket.sent.length - 1]).toMatchObject({linear_mps:0,angular_rps:0}); expect(Socket.sent.filter(v=>v.linear_mps===0)).toHaveLength(1) })
test('reset sends lease_id in the JSON body', async () => { await resetStop('all', 'lease-1'); const options = vi.mocked(fetch).mock.calls[0][1] as RequestInit; expect(JSON.parse(options.body as string)).toMatchObject({ lease_id: 'lease-1', target: 'all' }) })
test('stop polling ends on failed command without falsely confirming', async () => { const mock=vi.mocked(fetch); mock.mockResolvedValueOnce(new Response(JSON.stringify({ command_id:'cmd-f', state:'ACCEPTED' }), { status:202 })).mockResolvedValueOnce(new Response(JSON.stringify({ command_id:'cmd-f', state:'FAILED', targets:[] }), { status:200 })); render(<StopBar role="OPERATOR" lease={null} />); fireEvent.click(screen.getByText('전체 정지')); await act(async()=>{}); await act(async()=>{vi.advanceTimersByTime(250)}); expect(screen.getByText(/UNCONFIRMED/)).toBeInTheDocument() })
test('unmount sends one stop and clears cadence', () => { class Socket { readyState=1; static sent:any[]=[]; send(v:string){Socket.sent.push(JSON.parse(v))} close(){} } vi.stubGlobal('WebSocket', Socket); const view=render(<Teleop robotId="robot_1" lease="lease" mode="MANUAL" />); fireEvent.pointerDown(screen.getByText('전진')); view.unmount(); const count=Socket.sent.length; act(()=>vi.advanceTimersByTime(500)); expect(Socket.sent.length).toBe(count); expect(Socket.sent[count-1]).toMatchObject({linear_mps:0}) })
test('lease or mode change sends stop and disables control', () => { class Socket { readyState=1; static sent:any[]=[]; send(v:string){Socket.sent.push(JSON.parse(v))} close(){} } vi.stubGlobal('WebSocket', Socket); const view=render(<Teleop robotId="robot_1" lease="lease" mode="MANUAL" />); fireEvent.pointerDown(screen.getByText('전진')); view.rerender(<Teleop robotId="robot_1" lease={null} mode="IDLE" />); expect(Socket.sent[Socket.sent.length-1]).toMatchObject({linear_mps:0}); expect(screen.getByText('전진')).toBeDisabled() })
test('socket close immediately emits zero and clears interval', () => { class Socket { static all:Socket[]=[]; static sent:any[]=[]; readyState=1; send(v:string){Socket.sent.push(JSON.parse(v))} close(){} onclose=(_e:any)=>{}; constructor(){Socket.all.push(this)} } vi.stubGlobal('WebSocket', Socket); render(<Teleop robotId="robot_1" lease="lease" mode="MANUAL" />); fireEvent.pointerDown(screen.getByText('전진')); act(()=>Socket.all[0].onclose({code:1006})); const count=Socket.sent.length; act(()=>vi.advanceTimersByTime(500)); expect(Socket.sent.length).toBe(count); expect(Socket.sent[count-1]).toMatchObject({linear_mps:0}) })
